# Generated by Django 4.0.4 on 2022-04-25 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('058f48ea-e906-4ff3-b4a3-4c2f24416c79'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='catalogs.productsgroup', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Группа номенклатуры',
                'verbose_name_plural': 'Группы номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9c2f95e6-225c-4722-9a92-eed9c2b4b09a'), editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250, verbose_name='Наименование полное')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.productsgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
    ]
